// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProSoft.DMT.Api.Data.MsSql;

#nullable disable

namespace ProSoft.DMT.Api.Data.MsSql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241220213835_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProSoft.DMT.Data.Contracts.Entities.DockerHost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("Created")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FqdnIp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("VARCHAR(128)")
                        .HasColumnName("FqdnIp");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("SystemId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("VARCHAR(128)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SystemId" }, "UIX_data_DockerHosts_SystemId")
                        .IsUnique();

                    b.ToTable("DockerHosts", "data");
                });
#pragma warning restore 612, 618
        }
    }
}
